print("")
print("Menentukan Luas segitiga siku-siku")
print("")
print("Masukkan panjang alas")
a = int(input())
print("Masukkan tinggi segitiga")
b = int(input())
c = float((a * b) / 2)
print("Luas Segitiganya adalah " + str(c))
